baseURL = "https://thrive.uk/"
languageCode = "en-gb"
title = "Thrive | Leadership development & coaching collective"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Portfolio"
url = "portfolio"
weight = 3
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 4
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 5

# Site Params
[params]
logo = "images/logo.svg"
# logo_footer = "images/logo-footer.png"
logo_footer = "images/logo.svg"
nav_bar_dark = true
favicon_icon = "images/favicon.png"
favicon_icon_dark = "images/favicon-dark.png"
custom_stylesheets = []
dateFormat = "26 FEB 1994"
# Meta data
description = "Roxo Hugo themes | Design Agency Template by StaticMania"
author = "StaticMania"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://formspree.io/f/mbjnqqpd"

# Contact Form
[params.contactForm]
placeholder_first_name = "First Name"
placeholder_last_name = "Last Name"
placeholder_email = "Email"
placeholder_project_type = "Project Type"
placeholder_about_the_project = "About the Project"
send_message = "Send Message"

[[params.contactForm.projectType]]
value = "gd"
title = "Graphics Design"
[[params.contactForm.projectType]]
value = "wd"
title = "Web Design"

# Navbar Action Button
[params.navAction]
status = true
name = "Get in touch"
url = "contact"


# Banner Section
[params.banner]
enable = true
hero_dark = true
background_image = "images/backgrounds/hero-background.jpg"
heading = "We’re a Collective That Believes In Great Leaders"
tagline = "COACHING & LEADERSHIP DEVELOPMENT"
primary_button = "See Our Works"
primary_button_url = "portfolio"
secondary_button = "Connect with Us"
secondary_button_url = "contact"

[params.blog]
read_more = "read more"

[params.portfolio]
enable = true
title = "OUR RECENT WORKS"
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
view_project = "view project"
more_works = "MORE WORKS"
scroll_down = "scroll down"

[params.call_to_action]
enable = true
background_image = "images/backgrounds/cta-background.jpg"
title = "LET’S WORK TOGETHER"
primary_button = "Submit Query"
primary_button_url = "contact"
secondary_button = "Not Convinced"
secondary_button_url = "portfolio"

[params.footer]
qr_print = false
# Footer Contact Info
[params.footer.contactInfo]
title = "Contact Info"
# address = "713 Elmwood St.<br>Prior Lake, MN 55372"
phone = "+44 0000 123123"
email = "info@hithrive.uk"
# Footer Sitemap
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Company"
url = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Linkedin"
url = "https://www.linkedin.com/in/hildagardner/"
[[params.footer.social.link]]
name = "Medium"
url = "#"
[[params.footer.social.link]]
name = "Behance"
url = "#"
[[params.footer.social.link]]
name = "Dribbble"
url = "#"
# Footer Service
[params.footer.service]
title = "We help teams:"
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
[params.footer.back_to_top]
description = "I want to <br> visit again"
