baseURL = "https://thriveleadership.uk/"
languageCode = "en-gb"
title = "Thrive Leadership"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Services"
url = "services"
weight = 3
# [[menu.nav]]
# name = "Blog"
# url = "blog"
# weight = 4
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 5

# Site Params
[params]
logo = "images/logo.svg" # logo = "images/logo-crown-yellow.svg"

logo_footer = "images/logo.svg"
nav_bar_dark = false
favicon_icon = "images/favicon.png"
favicon_icon_dark = "images/favicon.png"
favicon_svg = "images/logo-crown-favicon.svg"
custom_stylesheets = []
dateFormat = "26 FEB 1994"
# Meta data
description = "Thrive Leadership | development & coaching"
author = "StaticMania"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://formspree.io/f/mbjnqqpd"

# Contact Form
[params.contactForm]
placeholder_first_name = "First Name"
placeholder_last_name = "Last Name"
placeholder_email = "Email"
placeholder_project_type = "Interested In..."
placeholder_about_the_project = "Your Message..."
send_message = "Send Message"

[[params.contactForm.projectType]]
value = "leadership-development"
title = "Leadership Development"
[[params.contactForm.projectType]]
value = "coaching"
title = "Executive Coaching"
[[params.contactForm.projectType]]
value = "other"
title = "Something else"

# Navbar Action Button
[params.navAction]
status = true
name = "Get in touch"
url = "contact"


# Banner Section
[params.banner]
enable = true
hero_dark = true
background_image = "images/backgrounds/pexels-tobiasbjorkli-2119706 3.jpg"
# background_image = "images/backgrounds/samuel-regan-asante-gVrATrhe7WM-unsplash.jpg"
# background_image = "images/backgrounds/erol-ahmed-aIYFR0vbADk-unsplash.jpg"
# background_image = "images/backgrounds/hero-background.jpg"
# background_image = "images/backgrounds/etienne-girardet-Xh6BpT-1tXo-unsplash.jpg"
# background_image = "images/backgrounds/pexels-mohamed-zarandah-217424204-11872428.jpg"
# background_image = "images/backgrounds/pexels-marinescu-mihai-2149909811-31993722.jpg"
# background_image = "images/backgrounds/pexels-alex-dos-santos-305643819-31842691.jpg"
# background_image = "images/backgrounds/nipun-haldar-JfBVu2c8ejk-unsplash.jpg"
# background_image = "images/backgrounds/tim-chow-9IcKPSQ9G5Q-unsplash.jpg"
# background_image = "images/backgrounds/scott-webb-GQD3Av_9A88-unsplash.jpg"
# background_image = "images/backgrounds/kendal-hnysCJrPpkc-unsplash.jpg"

heading = "Inspiring Leadership for Impactful Change"
tagline = "Leadership development & coaching"
enable_buttons = false
primary_button = "See Our Works"
primary_button_url = "services"
secondary_button = "Connect with Us"
secondary_button_url = "contact"

[params.blog]
read_more = "read more"

[params.services]
enable = false
title = "OUR RECENT WORKS"
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
view_project = "view service"
more_works = "MORE WORKS"
scroll_down = "scroll down"

[params.call_to_action]
enable = false
background_image = "images/backgrounds/cta-background.jpg"
title = "LET’S WORK TOGETHER"
primary_button = "Submit Query"
primary_button_url = "contact"
secondary_button = "Not Convinced"
secondary_button_url = "services"

[params.footer]
qr_print = false
# Footer Contact Info
[params.footer.contactInfo]
title = "Contact"
# address = "713 Elmwood St.<br>Prior Lake, MN 55372"
address = "Thrive Leadership<br>"
phone = "+44 0000 123123"
email = "info@thriveleadership.uk"
# Footer Sitemap
# [params.footer.sitemap]
# title = "Sitemap"
# [[params.footer.sitemap.link]]
# name = "About Company"
# url = "about"
# [[params.footer.sitemap.link]]
# name = "Services"
# url = "services"
# [[params.footer.sitemap.link]]
# name = "Blog"
# url = "blog"
# [[params.footer.sitemap.link]]
# name = "Contact"
# url = "contact"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Linkedin"
url = "https://www.linkedin.com/in/hildagardner/"
# [[params.footer.social.link]]
# name = "LinkedIn"
# url = "#"
# [[params.footer.social.link]]
# name = "Behance"
# url = "#"
# [[params.footer.social.link]]
# name = "Dribbble"
# url = "#"
# Footer Service
[params.footer.service]
title = "We help teams:"
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
[params.footer.back_to_top]
description = "Take me<br>back up"
